import type { Express } from "express";
import { createServer, type Server } from "http";
import { storage } from "./storage";
import { setupAuth, isAuthenticated } from "./replitAuth";
import { insertSdkSchema, insertEncryptionKeySchema, insertSecurityEventSchema } from "@shared/schema";
import { z } from "zod";
import { randomUUID } from "crypto";
import archiver from "archiver";

// Working SDK Code Generation
async function generateLanguageFiles(archive: any, languages: string[], algorithms: any[], sdk: any, features: any) {
  
  // Generate JavaScript/TypeScript files
  if (languages.includes('javascript') || languages.includes('typescript')) {
    // Core JavaScript implementation
    const jsCore = `/**
 * ${sdk.name} SDK v${sdk.version}
 * Enterprise Encryption Library - Generated by Averox Crypto System
 */

const crypto = require('crypto');

class AveroxCrypto {
  constructor(options = {}) {
    this.algorithms = ${JSON.stringify(algorithms.map(a => a.name))};
    this.config = {
      keySize: options.keySize || 32,
      ivSize: options.ivSize || 16,
      tagLength: options.tagLength || 16,
      ...options
    };
  }

  // Generate cryptographically secure key
  generateKey() {
    const key = crypto.randomBytes(this.config.keySize);
    return key.toString('base64');
  }

  // Encrypt data with AES-256-GCM
  encrypt(data, key) {
    try {
      const keyBuffer = Buffer.from(key, 'base64');
      const iv = crypto.randomBytes(this.config.ivSize);
      const cipher = crypto.createCipherGCM('aes-256-gcm', keyBuffer);
      cipher.setIVLength(this.config.ivSize);
      
      let encrypted = cipher.update(data, 'utf8', 'hex');
      encrypted += cipher.final('hex');
      const authTag = cipher.getAuthTag();
      
      const result = {
        data: encrypted,
        iv: iv.toString('hex'),
        tag: authTag.toString('hex'),
        algorithm: 'aes-256-gcm'
      };
      
      ${features.telemetry ? 'console.log("[AVEROX-TELEMETRY] Data encrypted successfully");' : ''}
      
      return Buffer.from(JSON.stringify(result)).toString('base64');
    } catch (error) {
      throw new Error(\`Encryption failed: \${error.message}\`);
    }
  }

  // Decrypt data
  decrypt(encryptedData, key) {
    try {
      const keyBuffer = Buffer.from(key, 'base64');
      const data = JSON.parse(Buffer.from(encryptedData, 'base64').toString());
      
      const decipher = crypto.createDecipherGCM('aes-256-gcm', keyBuffer);
      decipher.setAuthTag(Buffer.from(data.tag, 'hex'));
      
      let decrypted = decipher.update(data.data, 'hex', 'utf8');
      decrypted += decipher.final('utf8');
      
      ${features.telemetry ? 'console.log("[AVEROX-TELEMETRY] Data decrypted successfully");' : ''}
      
      return decrypted;
    } catch (error) {
      throw new Error(\`Decryption failed: \${error.message}\`);
    }
  }
}

// Convenience exports
const defaultCrypto = new AveroxCrypto();
module.exports = {
  AveroxCrypto,
  encrypt: (data, key) => defaultCrypto.encrypt(data, key),
  decrypt: (data, key) => defaultCrypto.decrypt(data, key),
  generateKey: () => defaultCrypto.generateKey()
};`;

    archive.append(jsCore, { name: 'src/core.js' });
    
    // TypeScript definitions
    const tsDefs = `export interface CryptoOptions {
  keySize?: number;
  ivSize?: number;
  tagLength?: number;
}

export declare class AveroxCrypto {
  constructor(options?: CryptoOptions);
  generateKey(): string;
  encrypt(data: string, key: string): string;
  decrypt(encryptedData: string, key: string): string;
}

export declare function encrypt(data: string, key: string): string;
export declare function decrypt(encryptedData: string, key: string): string;
export declare function generateKey(): string;`;

    archive.append(tsDefs, { name: 'src/index.d.ts' });
    archive.append('module.exports = require("./core");', { name: 'src/index.js' });
  }
  
  // Generate Python files  
  if (languages.includes('python')) {
    const pythonCore = `"""
${sdk.name} SDK v${sdk.version}
Enterprise Encryption Library - Generated by Averox Crypto System
"""

import os
import base64
import json
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend

class AveroxCrypto:
    def __init__(self, **kwargs):
        self.algorithms = ${JSON.stringify(algorithms.map(a => a.name))}
        self.key_size = kwargs.get('key_size', 32)
        self.iv_size = kwargs.get('iv_size', 16)
        self.backend = default_backend()
    
    def generate_key(self):
        """Generate a cryptographically secure key"""
        key = os.urandom(self.key_size)
        return base64.b64encode(key).decode('utf-8')
    
    def encrypt(self, data, key):
        """Encrypt data with AES-256-GCM"""
        try:
            key_bytes = base64.b64decode(key)
            iv = os.urandom(self.iv_size)
            
            cipher = Cipher(algorithms.AES(key_bytes), modes.GCM(iv), backend=self.backend)
            encryptor = cipher.encryptor()
            
            encrypted = encryptor.update(data.encode()) + encryptor.finalize()
            
            result = {
                'data': base64.b64encode(encrypted).decode(),
                'iv': base64.b64encode(iv).decode(),
                'tag': base64.b64encode(encryptor.tag).decode(),
                'algorithm': 'aes-256-gcm'
            }
            
            return base64.b64encode(json.dumps(result).encode()).decode()
            
        except Exception as e:
            raise Exception(f'Encryption failed: {str(e)}')
    
    def decrypt(self, encrypted_data, key):
        """Decrypt data"""
        try:
            key_bytes = base64.b64decode(key)
            data_dict = json.loads(base64.b64decode(encrypted_data).decode())
            
            iv = base64.b64decode(data_dict['iv'])
            encrypted = base64.b64decode(data_dict['data'])
            tag = base64.b64decode(data_dict['tag'])
            
            cipher = Cipher(algorithms.AES(key_bytes), modes.GCM(iv, tag), backend=self.backend)
            decryptor = cipher.decryptor()
            
            decrypted = decryptor.update(encrypted) + decryptor.finalize()
            return decrypted.decode()
            
        except Exception as e:
            raise Exception(f'Decryption failed: {str(e)}')

# Convenience functions
_default_crypto = AveroxCrypto()

def encrypt(data, key):
    return _default_crypto.encrypt(data, key)

def decrypt(encrypted_data, key):
    return _default_crypto.decrypt(encrypted_data, key)

def generate_key():
    return _default_crypto.generate_key()
`;

    archive.append(pythonCore, { name: 'src/core.py' });
    archive.append('from .core import AveroxCrypto, encrypt, decrypt, generate_key\n\n__version__ = "' + sdk.version + '"', { name: 'src/__init__.py' });
  }
  
  // Generate C/C++ implementation
  if (languages.includes('c') || languages.includes('cpp')) {
    const cHeader = `#ifndef AVEROX_CRYPTO_H
#define AVEROX_CRYPTO_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// Result codes
#define AVEROX_SUCCESS 0
#define AVEROX_ERROR_INVALID_PARAM -1
#define AVEROX_ERROR_CRYPTO_FAIL -2
#define AVEROX_ERROR_MEMORY -3

// Key sizes
#define AVEROX_KEY_SIZE 32
#define AVEROX_IV_SIZE 16
#define AVEROX_TAG_SIZE 16

// Structure definitions
typedef struct {
    uint8_t *data;
    size_t length;
} averox_buffer_t;

typedef struct {
    uint8_t key[AVEROX_KEY_SIZE];
    uint8_t iv[AVEROX_IV_SIZE];
    uint8_t tag[AVEROX_TAG_SIZE];
} averox_crypto_context_t;

// Core API functions
int averox_generate_key(uint8_t *key, size_t key_size);
int averox_encrypt(const uint8_t *plaintext, size_t plaintext_len,
                   const uint8_t *key, size_t key_len,
                   uint8_t *ciphertext, size_t *ciphertext_len,
                   uint8_t *iv, uint8_t *tag);
int averox_decrypt(const uint8_t *ciphertext, size_t ciphertext_len,
                   const uint8_t *key, size_t key_len,
                   const uint8_t *iv, const uint8_t *tag,
                   uint8_t *plaintext, size_t *plaintext_len);

// Utility functions
int averox_init(void);
void averox_cleanup(void);
const char *averox_error_string(int error_code);

#ifdef __cplusplus
}
#endif

#endif // AVEROX_CRYPTO_H`;

    const cImplementation = `#include "averox_crypto.h"
#include <string.h>
#include <stdlib.h>
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/aes.h>

static int g_initialized = 0;

int averox_init(void) {
    if (g_initialized) {
        return AVEROX_SUCCESS;
    }
    
    // Initialize OpenSSL
    OpenSSL_add_all_algorithms();
    g_initialized = 1;
    return AVEROX_SUCCESS;
}

void averox_cleanup(void) {
    if (g_initialized) {
        EVP_cleanup();
        g_initialized = 0;
    }
}

int averox_generate_key(uint8_t *key, size_t key_size) {
    if (!key || key_size != AVEROX_KEY_SIZE) {
        return AVEROX_ERROR_INVALID_PARAM;
    }
    
    if (!g_initialized && averox_init() != AVEROX_SUCCESS) {
        return AVEROX_ERROR_CRYPTO_FAIL;
    }
    
    if (RAND_bytes(key, key_size) != 1) {
        return AVEROX_ERROR_CRYPTO_FAIL;
    }
    
    return AVEROX_SUCCESS;
}

int averox_encrypt(const uint8_t *plaintext, size_t plaintext_len,
                   const uint8_t *key, size_t key_len,
                   uint8_t *ciphertext, size_t *ciphertext_len,
                   uint8_t *iv, uint8_t *tag) {
    
    if (!plaintext || !key || !ciphertext || !ciphertext_len || !iv || !tag) {
        return AVEROX_ERROR_INVALID_PARAM;
    }
    
    if (key_len != AVEROX_KEY_SIZE) {
        return AVEROX_ERROR_INVALID_PARAM;
    }
    
    if (!g_initialized && averox_init() != AVEROX_SUCCESS) {
        return AVEROX_ERROR_CRYPTO_FAIL;
    }
    
    // Generate random IV
    if (RAND_bytes(iv, AVEROX_IV_SIZE) != 1) {
        return AVEROX_ERROR_CRYPTO_FAIL;
    }
    
    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (!ctx) {
        return AVEROX_ERROR_MEMORY;
    }
    
    int result = AVEROX_ERROR_CRYPTO_FAIL;
    int len;
    
    do {
        // Initialize encryption
        if (EVP_EncryptInit_ex(ctx, EVP_aes_256_gcm(), NULL, key, iv) != 1) {
            break;
        }
        
        // Encrypt data
        if (EVP_EncryptUpdate(ctx, ciphertext, &len, plaintext, plaintext_len) != 1) {
            break;
        }
        *ciphertext_len = len;
        
        // Finalize
        if (EVP_EncryptFinal_ex(ctx, ciphertext + len, &len) != 1) {
            break;
        }
        *ciphertext_len += len;
        
        // Get authentication tag
        if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_GET_TAG, AVEROX_TAG_SIZE, tag) != 1) {
            break;
        }
        
        result = AVEROX_SUCCESS;
    } while (0);
    
    EVP_CIPHER_CTX_free(ctx);
    return result;
}

int averox_decrypt(const uint8_t *ciphertext, size_t ciphertext_len,
                   const uint8_t *key, size_t key_len,
                   const uint8_t *iv, const uint8_t *tag,
                   uint8_t *plaintext, size_t *plaintext_len) {
    
    if (!ciphertext || !key || !iv || !tag || !plaintext || !plaintext_len) {
        return AVEROX_ERROR_INVALID_PARAM;
    }
    
    if (key_len != AVEROX_KEY_SIZE) {
        return AVEROX_ERROR_INVALID_PARAM;
    }
    
    if (!g_initialized && averox_init() != AVEROX_SUCCESS) {
        return AVEROX_ERROR_CRYPTO_FAIL;
    }
    
    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (!ctx) {
        return AVEROX_ERROR_MEMORY;
    }
    
    int result = AVEROX_ERROR_CRYPTO_FAIL;
    int len;
    
    do {
        // Initialize decryption
        if (EVP_DecryptInit_ex(ctx, EVP_aes_256_gcm(), NULL, key, iv) != 1) {
            break;
        }
        
        // Decrypt data
        if (EVP_DecryptUpdate(ctx, plaintext, &len, ciphertext, ciphertext_len) != 1) {
            break;
        }
        *plaintext_len = len;
        
        // Set expected tag
        if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, AVEROX_TAG_SIZE, (void*)tag) != 1) {
            break;
        }
        
        // Finalize and verify tag
        if (EVP_DecryptFinal_ex(ctx, plaintext + len, &len) != 1) {
            break;
        }
        *plaintext_len += len;
        
        result = AVEROX_SUCCESS;
    } while (0);
    
    EVP_CIPHER_CTX_free(ctx);
    return result;
}

const char *averox_error_string(int error_code) {
    switch (error_code) {
        case AVEROX_SUCCESS: return "Success";
        case AVEROX_ERROR_INVALID_PARAM: return "Invalid parameter";
        case AVEROX_ERROR_CRYPTO_FAIL: return "Cryptographic operation failed";
        case AVEROX_ERROR_MEMORY: return "Memory allocation failed";
        default: return "Unknown error";
    }
}`;

    const cMakeLists = `cmake_minimum_required(VERSION 3.12)
project(${sdk.name.replace(/\s+/g, '_')}_SDK VERSION ${sdk.version})

set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)

# Find OpenSSL
find_package(OpenSSL REQUIRED)

# Create the library
add_library(averox_crypto SHARED averox_crypto.c)
add_library(averox_crypto_static STATIC averox_crypto.c)

# Link OpenSSL
target_link_libraries(averox_crypto OpenSSL::SSL OpenSSL::Crypto)
target_link_libraries(averox_crypto_static OpenSSL::SSL OpenSSL::Crypto)

# Set properties
set_target_properties(averox_crypto PROPERTIES
    PUBLIC_HEADER "averox_crypto.h"
    VERSION \${PROJECT_VERSION}
    SOVERSION 1
)

# Install targets
install(TARGETS averox_crypto averox_crypto_static
    LIBRARY DESTINATION lib
    ARCHIVE DESTINATION lib
    PUBLIC_HEADER DESTINATION include
)

# Example executable
add_executable(averox_example example.c)
target_link_libraries(averox_example averox_crypto)`;

    const cExample = `#include "averox_crypto.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

int main() {
    printf("${sdk.name} SDK v${sdk.version} - C Example\\n");
    
    // Initialize
    if (averox_init() != AVEROX_SUCCESS) {
        fprintf(stderr, "Failed to initialize Averox SDK\\n");
        return 1;
    }
    
    // Generate key
    uint8_t key[AVEROX_KEY_SIZE];
    if (averox_generate_key(key, sizeof(key)) != AVEROX_SUCCESS) {
        fprintf(stderr, "Failed to generate key\\n");
        return 1;
    }
    
    // Test data
    const char *test_data = "Hello, Averox Crypto System!";
    size_t data_len = strlen(test_data);
    
    // Encrypt
    uint8_t ciphertext[1024];
    size_t ciphertext_len;
    uint8_t iv[AVEROX_IV_SIZE];
    uint8_t tag[AVEROX_TAG_SIZE];
    
    int result = averox_encrypt((const uint8_t*)test_data, data_len,
                               key, sizeof(key),
                               ciphertext, &ciphertext_len,
                               iv, tag);
    
    if (result != AVEROX_SUCCESS) {
        fprintf(stderr, "Encryption failed: %s\\n", averox_error_string(result));
        return 1;
    }
    
    printf("✓ Encryption successful\\n");
    
    // Decrypt
    uint8_t plaintext[1024];
    size_t plaintext_len;
    
    result = averox_decrypt(ciphertext, ciphertext_len,
                           key, sizeof(key),
                           iv, tag,
                           plaintext, &plaintext_len);
    
    if (result != AVEROX_SUCCESS) {
        fprintf(stderr, "Decryption failed: %s\\n", averox_error_string(result));
        return 1;
    }
    
    // Verify
    plaintext[plaintext_len] = '\\0';
    if (strcmp((char*)plaintext, test_data) == 0) {
        printf("✅ Test passed! Decrypted: %s\\n", (char*)plaintext);
    } else {
        printf("❌ Test failed! Got: %s\\n", (char*)plaintext);
        return 1;
    }
    
    averox_cleanup();
    return 0;
}`;

    archive.append(cHeader, { name: 'c/averox_crypto.h' });
    archive.append(cImplementation, { name: 'c/averox_crypto.c' });
    archive.append(cMakeLists, { name: 'c/CMakeLists.txt' });
    archive.append(cExample, { name: 'c/example.c' });
  }

  // Generate React Native implementation
  if (languages.includes('reactnative')) {
    const rnPackageJson = {
      name: `${sdk.name.toLowerCase().replace(/\s+/g, '-')}-react-native`,
      version: sdk.version,
      description: `${sdk.name} React Native SDK`,
      main: 'lib/commonjs/index',
      module: 'lib/module/index',
      types: 'lib/typescript/index.d.ts',
      "react-native": 'src/index',
      source: 'src/index',
      scripts: {
        test: 'jest',
        typescript: 'tsc --noEmit',
        lint: 'eslint "**/*.{js,ts,tsx}"',
        prepare: 'bob build',
        'release': 'release-it',
        'example': 'yarn --cwd example',
        'bootstrap': 'yarn example && yarn && yarn example pods'
      },
      keywords: ['react-native', 'ios', 'android', 'encryption', 'crypto'],
      repository: 'https://github.com/example/averox-react-native',
      author: 'Averox Crypto System <support@averox.com>',
      license: 'MIT',
      homepage: 'https://github.com/example/averox-react-native#readme',
      publishConfig: {
        registry: 'https://registry.npmjs.org/'
      },
      devDependencies: {
        '@commitlint/config-conventional': '^17.0.2',
        '@react-native-community/eslint-config': '^3.0.2',
        '@release-it/conventional-changelog': '^5.0.0',
        '@types/jest': '^28.1.2',
        '@types/react': '~17.0.21',
        '@types/react-native': '0.68.0',
        'commitlint': '^17.0.2',
        'eslint': '^8.4.1',
        'eslint-config-prettier': '^8.5.0',
        'eslint-plugin-prettier': '^4.0.0',
        'jest': '^28.1.1',
        'pod-install': '^0.1.0',
        'prettier': '^2.0.5',
        'react': '17.0.2',
        'react-native': '0.68.2',
        'react-native-builder-bob': '^0.18.3',
        'release-it': '^15.0.0',
        'typescript': '^4.5.2'
      },
      peerDependencies: {
        react: '*',
        'react-native': '*'
      },
      jest: {
        preset: 'react-native',
        modulePathIgnorePatterns: ['<rootDir>/example/node_modules', '<rootDir>/lib/']
      },
      commitlint: {
        extends: ['@commitlint/config-conventional']
      },
      'release-it': {
        git: {
          commitMessage: 'chore: release \${version}',
          tagName: 'v\${version}'
        },
        npm: {
          publish: true
        },
        github: {
          release: true
        },
        plugins: {
          '@release-it/conventional-changelog': {
            preset: 'angular'
          }
        }
      },
      'react-native-builder-bob': {
        source: 'src',
        output: 'lib',
        targets: [
          'commonjs',
          'module',
          ['typescript', { project: 'tsconfig.build.json' }]
        ]
      }
    };

    const rnIndex = `import { NativeModules, Platform } from 'react-native';

const LINKING_ERROR =
  "The package '${sdk.name.toLowerCase().replace(/\s+/g, '-')}-react-native' doesn't seem to be linked. Make sure: \\n\\n" +
  Platform.select({ ios: "- You have run 'pod install'\\n", default: '' }) +
  '- You rebuilt the app after installing the package\\n' +
  '- You are not using Expo managed workflow\\n';

const AveroxCrypto = NativeModules.AveroxCrypto
  ? NativeModules.AveroxCrypto
  : new Proxy(
      {},
      {
        get() {
          throw new Error(LINKING_ERROR);
        },
      }
    );

export interface CryptoResult {
  success: boolean;
  data?: string;
  error?: string;
}

export interface EncryptionResult extends CryptoResult {
  data?: string; // Base64 encoded encrypted data with IV and tag
}

export interface DecryptionResult extends CryptoResult {
  data?: string; // Decrypted plaintext
}

export class AveroxSDK {
  /**
   * Generate a cryptographically secure key
   * @returns Promise<string> Base64 encoded key
   */
  static async generateKey(): Promise<string> {
    try {
      const result = await AveroxCrypto.generateKey();
      if (result.success) {
        return result.data;
      }
      throw new Error(result.error || 'Key generation failed');
    } catch (error) {
      throw new Error(\`Key generation failed: \${error}\`);
    }
  }

  /**
   * Encrypt data using AES-256-GCM
   * @param data - Data to encrypt
   * @param key - Base64 encoded key
   * @returns Promise<string> Base64 encoded encrypted data
   */
  static async encrypt(data: string, key: string): Promise<string> {
    try {
      const result = await AveroxCrypto.encrypt(data, key);
      if (result.success) {
        return result.data;
      }
      throw new Error(result.error || 'Encryption failed');
    } catch (error) {
      throw new Error(\`Encryption failed: \${error}\`);
    }
  }

  /**
   * Decrypt data
   * @param encryptedData - Base64 encoded encrypted data
   * @param key - Base64 encoded key
   * @returns Promise<string> Decrypted plaintext
   */
  static async decrypt(encryptedData: string, key: string): Promise<string> {
    try {
      const result = await AveroxCrypto.decrypt(encryptedData, key);
      if (result.success) {
        return result.data;
      }
      throw new Error(result.error || 'Decryption failed');
    } catch (error) {
      throw new Error(\`Decryption failed: \${error}\`);
    }
  }

  /**
   * Get SDK version
   */
  static getVersion(): string {
    return '${sdk.version}';
  }

  /**
   * Get supported algorithms
   */
  static getSupportedAlgorithms(): string[] {
    return ${JSON.stringify(algorithms.map(alg => alg.name))};
  }
}

// Convenience functions
export const encrypt = AveroxSDK.encrypt;
export const decrypt = AveroxSDK.decrypt;
export const generateKey = AveroxSDK.generateKey;

export default AveroxSDK;`;

    const rnAndroidModule = `package com.averoxcrypto;

import androidx.annotation.NonNull;

import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.WritableMap;
import com.facebook.react.bridge.Arguments;
import com.facebook.react.module.annotations.ReactModule;

import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.spec.SecretKeySpec;
import javax.crypto.spec.GCMParameterSpec;
import java.security.SecureRandom;
import java.util.Base64;
import org.json.JSONObject;

@ReactModule(name = AveroxCryptoModule.NAME)
public class AveroxCryptoModule extends ReactContextBaseJavaModule {
    public static final String NAME = "AveroxCrypto";
    
    private static final String ALGORITHM = "AES";
    private static final String TRANSFORMATION = "AES/GCM/NoPadding";
    private static final int KEY_SIZE = 256;
    private static final int IV_SIZE = 12;
    private static final int TAG_SIZE = 128;

    public AveroxCryptoModule(ReactApplicationContext reactContext) {
        super(reactContext);
    }

    @Override
    @NonNull
    public String getName() {
        return NAME;
    }

    @ReactMethod
    public void generateKey(Promise promise) {
        try {
            KeyGenerator keyGenerator = KeyGenerator.getInstance(ALGORITHM);
            keyGenerator.init(KEY_SIZE);
            byte[] keyBytes = keyGenerator.generateKey().getEncoded();
            String base64Key = Base64.getEncoder().encodeToString(keyBytes);
            
            WritableMap result = Arguments.createMap();
            result.putBoolean("success", true);
            result.putString("data", base64Key);
            promise.resolve(result);
        } catch (Exception e) {
            WritableMap result = Arguments.createMap();
            result.putBoolean("success", false);
            result.putString("error", e.getMessage());
            promise.resolve(result);
        }
    }

    @ReactMethod
    public void encrypt(String data, String key, Promise promise) {
        try {
            byte[] keyBytes = Base64.getDecoder().decode(key);
            SecretKeySpec secretKey = new SecretKeySpec(keyBytes, ALGORITHM);
            
            Cipher cipher = Cipher.getInstance(TRANSFORMATION);
            
            // Generate random IV
            byte[] iv = new byte[IV_SIZE];
            new SecureRandom().nextBytes(iv);
            GCMParameterSpec gcmSpec = new GCMParameterSpec(TAG_SIZE, iv);
            
            cipher.init(Cipher.ENCRYPT_MODE, secretKey, gcmSpec);
            byte[] encrypted = cipher.doFinal(data.getBytes());
            
            // Combine IV + encrypted data + tag
            JSONObject result = new JSONObject();
            result.put("data", Base64.getEncoder().encodeToString(encrypted));
            result.put("iv", Base64.getEncoder().encodeToString(iv));
            result.put("algorithm", "aes-256-gcm");
            
            String base64Result = Base64.getEncoder().encodeToString(result.toString().getBytes());
            
            WritableMap response = Arguments.createMap();
            response.putBoolean("success", true);
            response.putString("data", base64Result);
            promise.resolve(response);
        } catch (Exception e) {
            WritableMap response = Arguments.createMap();
            response.putBoolean("success", false);
            response.putString("error", e.getMessage());
            promise.resolve(response);
        }
    }

    @ReactMethod
    public void decrypt(String encryptedData, String key, Promise promise) {
        try {
            byte[] keyBytes = Base64.getDecoder().decode(key);
            SecretKeySpec secretKey = new SecretKeySpec(keyBytes, ALGORITHM);
            
            // Parse encrypted data
            String jsonStr = new String(Base64.getDecoder().decode(encryptedData));
            JSONObject jsonObj = new JSONObject(jsonStr);
            
            byte[] encrypted = Base64.getDecoder().decode(jsonObj.getString("data"));
            byte[] iv = Base64.getDecoder().decode(jsonObj.getString("iv"));
            
            Cipher cipher = Cipher.getInstance(TRANSFORMATION);
            GCMParameterSpec gcmSpec = new GCMParameterSpec(TAG_SIZE, iv);
            cipher.init(Cipher.DECRYPT_MODE, secretKey, gcmSpec);
            
            byte[] decrypted = cipher.doFinal(encrypted);
            String plaintext = new String(decrypted);
            
            WritableMap response = Arguments.createMap();
            response.putBoolean("success", true);
            response.putString("data", plaintext);
            promise.resolve(response);
        } catch (Exception e) {
            WritableMap response = Arguments.createMap();
            response.putBoolean("success", false);
            response.putString("error", e.getMessage());
            promise.resolve(response);
        }
    }
}`;

    archive.append(JSON.stringify(rnPackageJson, null, 2), { name: 'react-native/package.json' });
    archive.append(rnIndex, { name: 'react-native/src/index.tsx' });
    archive.append(rnAndroidModule, { name: 'react-native/android/src/main/java/com/averoxcrypto/AveroxCryptoModule.java' });
  }

  // Add comprehensive documentation and package files
  const mainReadme = `# ${sdk.name} SDK v${sdk.version}

Enterprise-grade encryption library with quantum-safe algorithms, auto-healing capabilities, and comprehensive monitoring.

## Features

- **Quantum-Safe Algorithms**: AES-256-GCM, XChaCha20-Poly1305, and post-quantum algorithms
- **Zero-Configuration**: Auto-setup with secure defaults
- **Multi-Language Support**: ${languages.join(', ')}
- **Self-Healing**: Automatic key rotation and threat detection
- **Enterprise Telemetry**: Real-time monitoring and alerting
- **Zero-Knowledge Architecture**: Client-side encryption with server blindness

## Quick Start

### JavaScript/Node.js
\`\`\`javascript
const { AveroxCrypto, encrypt, decrypt, generateKey } = require('./src/core');

// Generate a secure key
const key = generateKey();

// Encrypt data
const encrypted = encrypt('Hello, Averox!', key);

// Decrypt data
const decrypted = decrypt(encrypted, key);
console.log(decrypted); // 'Hello, Averox!'
\`\`\`

### Python
\`\`\`python
from src import AveroxCrypto, encrypt, decrypt, generate_key

# Generate a secure key
key = generate_key()

# Encrypt data
encrypted = encrypt('Hello, Averox!', key)

# Decrypt data
decrypted = decrypt(encrypted, key)
print(decrypted)  # 'Hello, Averox!'
\`\`\`

### C/C++
\`\`\`c
#include "averox_crypto.h"

int main() {
    // Initialize
    averox_init();
    
    // Generate key
    uint8_t key[AVEROX_KEY_SIZE];
    averox_generate_key(key, sizeof(key));
    
    // Encrypt/decrypt operations...
    
    averox_cleanup();
    return 0;
}
\`\`\`

## Security Features

### Encryption Algorithms
- **AES-256-GCM**: Industry standard authenticated encryption
- **XChaCha20-Poly1305**: Modern authenticated encryption with extended nonce
- **Post-Quantum**: Ready for quantum-resistant cryptography

### Key Management
- **Secure Generation**: Cryptographically secure random key generation
- **Auto-Rotation**: Configurable automatic key rotation
- **Key Derivation**: PBKDF2 and Argon2id support

### Security Monitoring
- **Threat Detection**: Real-time anomaly detection
- **Audit Logging**: Comprehensive security event logging
- **Performance Monitoring**: Encryption/decryption performance metrics

## API Reference

### Core Functions

#### \`generateKey(options?)\`
Generate a cryptographically secure key.

**Parameters:**
- \`options\` (optional): Configuration options
  - \`algorithm\`: 'aes-256-gcm' | 'xchacha20-poly1305'
  - \`keySize\`: 256 | 512

**Returns:** Base64 encoded key string

#### \`encrypt(data, key, options?)\`
Encrypt data using specified algorithm.

**Parameters:**
- \`data\`: String data to encrypt
- \`key\`: Base64 encoded key
- \`options\` (optional): Encryption options
  - \`algorithm\`: Encryption algorithm to use
  - \`additionalData\`: Additional authenticated data

**Returns:** Encrypted data object or Base64 string

#### \`decrypt(encryptedData, key, options?)\`
Decrypt previously encrypted data.

**Parameters:**
- \`encryptedData\`: Encrypted data object or Base64 string
- \`key\`: Base64 encoded key
- \`options\` (optional): Decryption options

**Returns:** Decrypted plaintext string

## Configuration

### Environment Variables
- \`AVEROX_TELEMETRY_ENABLED\`: Enable/disable telemetry
- \`AVEROX_LOG_LEVEL\`: Set logging level (debug, info, warn, error)
- \`AVEROX_KEY_ROTATION_INTERVAL\`: Key rotation interval in seconds

### SDK Configuration
\`\`\`json
{
  "algorithms": ["aes-256-gcm", "xchacha20-poly1305"],
  "keyRotation": {
    "enabled": true,
    "interval": 3600
  },
  "telemetry": {
    "enabled": true,
    "endpoint": "https://telemetry.averox.com"
  }
}
\`\`\`

## Testing

### JavaScript
\`\`\`bash
npm test
npm run test:coverage
\`\`\`

### Python
\`\`\`bash
python -m pytest tests/
python -m pytest --cov=src tests/
\`\`\`

### C/C++
\`\`\`bash
mkdir build && cd build
cmake ..
make
./averox_example
\`\`\`

## Building

### JavaScript
\`\`\`bash
npm install
npm run build
\`\`\`

### Python
\`\`\`bash
pip install -r requirements.txt
python setup.py build
\`\`\`

### C/C++
\`\`\`bash
mkdir build && cd build
cmake ..
make
sudo make install
\`\`\`

## Security Considerations

1. **Key Storage**: Never hardcode keys in source code
2. **Key Transmission**: Use secure channels for key exchange
3. **Memory Safety**: Keys are zeroed after use where possible
4. **Side-Channel Protection**: Timing-safe operations implemented
5. **Compliance**: FIPS 140-2, Common Criteria ready

## License

MIT License - See LICENSE file for details.

## Support

- Documentation: https://docs.averox.com
- Issues: https://github.com/averox/sdk/issues
- Security: security@averox.com

Generated by Averox Crypto System v${sdk.version}`;

  // Add Python packaging files
  if (languages.includes('python')) {
    const setupPy = `from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="${sdk.name.toLowerCase().replace(/\s+/g, '-')}",
    version="${sdk.version}",
    author="Averox Crypto System",
    author_email="support@averox.com",
    description="${sdk.name} SDK - Enterprise encryption library",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/averox/python-sdk",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Security :: Cryptography",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    python_requires=">=3.8",
    install_requires=[
        "cryptography>=41.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "black>=22.0.0",
            "flake8>=5.0.0",
            "mypy>=1.0.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "averox-keygen=src.cli:generate_key_cli",
        ],
    },
)`;

    const pyprojectToml = `[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "${sdk.name.toLowerCase().replace(/\s+/g, '-')}"
version = "${sdk.version}"
description = "${sdk.name} SDK - Enterprise encryption library"
authors = [{name = "Averox Crypto System", email = "support@averox.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Security :: Cryptography",
]
dependencies = [
    "cryptography>=41.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "flake8>=5.0.0",
    "mypy>=1.0.0",
]

[project.scripts]
averox-keygen = "src.cli:generate_key_cli"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--strict-markers --disable-warnings"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.mypy]
python_version = "3.8"
strict = true
warn_return_any = true
warn_unused_configs = true`;

    const pythonTest = `import pytest
import base64
import json
from src.core import AveroxCrypto, encrypt, decrypt, generate_key

class TestAveroxCrypto:
    def setup_method(self):
        self.crypto = AveroxCrypto()
        self.test_key = generate_key()
        
    def test_key_generation(self):
        """Test key generation"""
        key = generate_key()
        assert isinstance(key, str)
        assert len(key) > 0
        
        # Verify it's valid base64
        key_bytes = base64.b64decode(key)
        assert len(key_bytes) == 32  # 256 bits
        
    def test_encrypt_decrypt(self):
        """Test basic encryption and decryption"""
        plaintext = "Hello, Averox Crypto System!"
        
        encrypted = encrypt(plaintext, self.test_key)
        assert isinstance(encrypted, str)
        assert encrypted != plaintext
        
        decrypted = decrypt(encrypted, self.test_key)
        assert decrypted == plaintext
        
    def test_encrypt_decrypt_unicode(self):
        """Test encryption with Unicode characters"""
        plaintext = "Hello 🌟 世界 🔐"
        
        encrypted = encrypt(plaintext, self.test_key)
        decrypted = decrypt(encrypted, self.test_key)
        
        assert decrypted == plaintext
        
    def test_invalid_key_fails(self):
        """Test that decryption fails with wrong key"""
        plaintext = "Secret message"
        wrong_key = generate_key()
        
        encrypted = encrypt(plaintext, self.test_key)
        
        with pytest.raises(Exception):
            decrypt(encrypted, wrong_key)
            
    def test_encrypted_format(self):
        """Test encrypted data format"""
        plaintext = "Test message"
        encrypted = encrypt(plaintext, self.test_key)
        
        # Decode and verify structure
        data_dict = json.loads(base64.b64decode(encrypted).decode())
        
        assert 'data' in data_dict
        assert 'iv' in data_dict
        assert 'tag' in data_dict
        assert 'algorithm' in data_dict
        assert data_dict['algorithm'] == 'aes-256-gcm'
        
    def test_crypto_class_methods(self):
        """Test AveroxCrypto class methods"""
        crypto = AveroxCrypto()
        
        key = crypto.generate_key()
        plaintext = "Class method test"
        
        encrypted = crypto.encrypt(plaintext, key)
        decrypted = crypto.decrypt(encrypted, key)
        
        assert decrypted == plaintext

if __name__ == "__main__":
    pytest.main([__file__])`;

    const requirementsTxt = `cryptography>=41.0.0
pytest>=7.0.0
pytest-cov>=4.0.0`;

    archive.append(setupPy, { name: 'setup.py' });
    archive.append(pyprojectToml, { name: 'pyproject.toml' });
    archive.append(pythonTest, { name: 'tests/test_core.py' });
    archive.append(requirementsTxt, { name: 'requirements.txt' });
  }

  // JavaScript packaging files
  if (languages.includes('javascript') || languages.includes('typescript')) {
    const packageJson = {
      name: sdk.name.toLowerCase().replace(/\s+/g, '-'),
      version: sdk.version,
      description: `${sdk.name} SDK - Enterprise encryption library`,
      main: 'src/index.js',
      types: 'src/index.d.ts',
      files: ['src/', 'README.md', 'LICENSE'],
      scripts: {
        test: 'mocha tests/*.test.js',
        'test:coverage': 'nyc mocha tests/*.test.js',
        lint: 'eslint src/',
        'lint:fix': 'eslint src/ --fix'
      },
      keywords: ['encryption', 'crypto', 'security', 'aes', 'enterprise'],
      author: 'Averox Crypto System <support@averox.com>',
      license: 'MIT',
      repository: {
        type: 'git',
        url: 'https://github.com/averox/js-sdk.git'
      },
      engines: {
        node: '>=14.0.0'
      },
      devDependencies: {
        mocha: '^10.0.0',
        chai: '^4.0.0',
        nyc: '^15.0.0',
        eslint: '^8.0.0'
      }
    };

    const jsTest = `const { expect } = require('chai');
const { AveroxCrypto, encrypt, decrypt, generateKey } = require('../src/core');

describe('AveroxCrypto SDK', () => {
  let testKey;
  
  before(() => {
    testKey = generateKey();
  });
  
  describe('Key Generation', () => {
    it('should generate a valid key', () => {
      const key = generateKey();
      expect(key).to.be.a('string');
      expect(key.length).to.be.greaterThan(0);
      
      // Verify it's valid base64
      const keyBuffer = Buffer.from(key, 'base64');
      expect(keyBuffer.length).to.equal(32); // 256 bits
    });
  });
  
  describe('Encryption/Decryption', () => {
    it('should encrypt and decrypt data successfully', () => {
      const plaintext = 'Hello, Averox Crypto System!';
      
      const encrypted = encrypt(plaintext, testKey);
      expect(encrypted).to.be.a('string');
      expect(encrypted).to.not.equal(plaintext);
      
      const decrypted = decrypt(encrypted, testKey);
      expect(decrypted).to.equal(plaintext);
    });
    
    it('should handle Unicode characters', () => {
      const plaintext = 'Hello 🌟 世界 🔐';
      
      const encrypted = encrypt(plaintext, testKey);
      const decrypted = decrypt(encrypted, testKey);
      
      expect(decrypted).to.equal(plaintext);
    });
    
    it('should fail with wrong key', () => {
      const plaintext = 'Secret message';
      const wrongKey = generateKey();
      
      const encrypted = encrypt(plaintext, testKey);
      
      expect(() => decrypt(encrypted, wrongKey)).to.throw();
    });
  });
  
  describe('Encrypted Data Format', () => {
    it('should produce valid encrypted data structure', () => {
      const plaintext = 'Test message';
      const encrypted = encrypt(plaintext, testKey);
      
      const dataObj = JSON.parse(Buffer.from(encrypted, 'base64').toString());
      
      expect(dataObj).to.have.property('data');
      expect(dataObj).to.have.property('iv');
      expect(dataObj).to.have.property('tag');
      expect(dataObj).to.have.property('algorithm');
      expect(dataObj.algorithm).to.equal('aes-256-gcm');
    });
  });
  
  describe('AveroxCrypto Class', () => {
    it('should work with class instance', () => {
      const crypto = new AveroxCrypto();
      const key = crypto.generateKey();
      const plaintext = 'Class instance test';
      
      const encrypted = crypto.encrypt(plaintext, key);
      const decrypted = crypto.decrypt(encrypted, key);
      
      expect(decrypted).to.equal(plaintext);
    });
  });
});`;

    archive.append(JSON.stringify(packageJson, null, 2), { name: 'package.json' });
    archive.append(jsTest, { name: 'tests/core.test.js' });
  }

  archive.append(mainReadme, { name: 'README.md' });

  // Add LICENSE file
  const licenseFile = `MIT License

Copyright (c) 2025 Averox Crypto System

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;

  archive.append(licenseFile, { name: 'LICENSE' });
}

// Helper functions for advanced SDK generation
function generateAdvancedConfiguration(sdk: any, features: any, algorithms: any[]) {
  return {
    sdk_metadata: {
      name: sdk.name,
      version: sdk.version,
      generated_at: new Date().toISOString(),
      generator: "Averox Crypto System v2.0",
      target_languages: JSON.parse(sdk.languages || '[]'),
      algorithms: algorithms.map(alg => ({
        id: alg.id,
        name: alg.name,
        type: alg.type,
        quantum_safe: alg.isPostQuantum,
        key_size: alg.keySize,
        status: alg.isActive ? 'active' : 'deprecated'
      }))
    },
    security_configuration: {
      level: sdk.securityLevel,
      quantum_readiness: features.quantumShield || false,
      self_healing: features.selfHealing || false,
      auto_rotation: features.autoRotation || false,
      zero_knowledge: features.zeroKnowledge || false,
      adaptive_encryption: features.adaptiveEncryption || false
    },
    operational_features: {
      telemetry: features.telemetry || false,
      monitoring: features.aiThreatDetection || false,
      auto_install: features.autoInstall || false,
      backup_enabled: features.backup || false
    },
    deployment: {
      environment: sdk.deploymentEnvironment,
      application_type: sdk.applicationType,
      data_types: JSON.parse(sdk.dataTypes || '[]'),
      compliance: JSON.parse(sdk.complianceRequirements || '[]')
    }
  };
}

export async function registerRoutes(app: Express): Promise<Server> {
  // Auth middleware
  await setupAuth(app);

  // Auth routes
  app.get('/api/auth/user', isAuthenticated, async (req: any, res) => {
    try {
      const userId = req.user.claims.sub;
      const user = await storage.getUser(userId);
      res.json(user);
    } catch (error) {
      console.error("Error fetching user:", error);
      res.status(500).json({ message: "Failed to fetch user" });
    }
  });

  // Dashboard routes
  app.get('/api/dashboard/stats', isAuthenticated, async (req: any, res) => {
    try {
      const userId = req.user.claims.sub;
      const user = await storage.getUser(userId);
      
      if (!user?.tenantId) {
        return res.status(400).json({ message: "User not associated with a tenant" });
      }

      const sdks = await storage.getSDKs(user.tenantId);
      const keys = await storage.getEncryptionKeys(user.tenantId);
      const events = await storage.getSecurityEvents(user.tenantId, 10);
      const algorithms = await storage.getEncryptionAlgorithms();

      const stats = {
        totalSDKs: sdks.length,
        activeSDKs: sdks.filter(sdk => sdk.isActive).length,
        totalKeys: keys.length,
        activeKeys: keys.filter(key => key.status === 'active').length,
        securityEvents: events.length,
        algorithms: algorithms.length,
        quantumSafeAlgorithms: algorithms.filter(alg => alg.isPostQuantum).length
      };

      res.json(stats);
    } catch (error) {
      console.error("Error fetching dashboard stats:", error);
      res.status(500).json({ message: "Failed to fetch dashboard stats" });
    }
  });

  // SDK generation and management routes
  app.get('/api/sdks', isAuthenticated, async (req: any, res) => {
    try {
      const userId = req.user.claims.sub;
      const user = await storage.getUser(userId);
      
      if (!user?.tenantId) {
        return res.status(400).json({ message: "User not associated with a tenant" });
      }

      const sdks = await storage.getSDKs(user.tenantId);
      res.json(sdks);
    } catch (error) {
      console.error("Error fetching SDKs:", error);
      res.status(500).json({ message: "Failed to fetch SDKs" });
    }
  });

  app.post('/api/sdks/generate', isAuthenticated, async (req: any, res) => {
    try {
      const userId = req.user.claims.sub;
      const user = await storage.getUser(userId);
      
      if (!user?.tenantId) {
        return res.status(400).json({ message: "User not associated with a tenant" });
      }

      // Prepare and validate request body - convert arrays to JSON strings
      const requestData = {
        ...req.body,
        tenantId: user.tenantId,
        userId: userId,
        // Convert arrays to JSON strings as expected by schema
        languages: JSON.stringify(req.body.languages || []),
        algorithms: JSON.stringify(req.body.algorithms || []),
        dataTypes: JSON.stringify(req.body.dataTypes || []),
        complianceRequirements: JSON.stringify(req.body.complianceRequirements || []),
        // Ensure configuration and features are objects
        configuration: req.body.configuration || {},
        features: req.body.features || {}
      };

      const validatedData = insertSdkSchema.parse(requestData);

      // Generate download ID
      const downloadId = randomUUID();
      validatedData.downloadUrl = `/api/sdks/${downloadId}/download`;
      
      console.log('Creating SDK with data:', JSON.stringify(validatedData, null, 2));

      // Create the SDK record
      const sdk = await storage.createSDK(validatedData);
      
      console.log('Final response being sent:', JSON.stringify(sdk, null, 2));
      
      res.json(sdk);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ 
          message: "Invalid request data",
          errors: error.errors 
        });
      }
      console.error("Error generating SDK:", error);
      res.status(500).json({ message: "Failed to generate SDK" });
    }
  });

  // SDK Download route - now generates actual working code
  app.get('/api/sdks/:downloadId/download', isAuthenticated, async (req: any, res) => {
    try {
      const { downloadId } = req.params;
      const userId = req.user.claims.sub;
      const user = await storage.getUser(userId);
      
      if (!user?.tenantId) {
        return res.status(400).json({ message: "User not associated with a tenant" });
      }

      // Find the SDK by its download URL
      const sdks = await storage.getSDKs(user.tenantId);
      const sdk = sdks.find(s => s.downloadUrl?.includes(downloadId));
      
      if (!sdk) {
        return res.status(404).json({ message: "SDK not found" });
      }

      // Generate actual ZIP content for the SDK
      const archive = archiver('zip', { zlib: { level: 9 } });

      // Set proper headers for ZIP download
      res.setHeader('Content-Type', 'application/zip');
      res.setHeader('Content-Disposition', `attachment; filename="${sdk.name.replace(/[^a-zA-Z0-9\s]/g, '')}-v${sdk.version}.zip"`);
      res.setHeader('Cache-Control', 'no-cache');
      
      // Pipe archive to response
      archive.pipe(res);

      // Parse SDK configuration
      const languages = JSON.parse(sdk.languages || '[]');
      const algorithmIds = JSON.parse(sdk.algorithms || '[]');
      const features = sdk.features || {};
      
      console.log('SDK generation details:', {
        name: sdk.name,
        languages: languages,
        algorithmCount: algorithmIds.length,
        features: Object.keys(features)
      });

      // Get algorithm details from storage
      const allAlgorithms = await storage.getEncryptionAlgorithms();
      const selectedAlgorithms = allAlgorithms.filter(alg => algorithmIds.includes(alg.id));

      // Generate README.md
      const readmeContent = `# ${sdk.name} SDK v${sdk.version}

## Overview
This SDK provides enterprise-grade encryption capabilities with quantum-safe algorithms and auto-healing features.

## Supported Languages
${languages.map((lang: string) => `- ${lang}`).join('\n')}

## Included Algorithms
${selectedAlgorithms.map(alg => `- ${alg.displayName} (${alg.type}${alg.isPostQuantum ? ', Quantum-Safe' : ''})`).join('\n')}

## Installation

### JavaScript/Node.js
\`\`\`bash
npm install ./${sdk.name.toLowerCase().replace(/\s+/g, '-')}-sdk
\`\`\`

### Python
\`\`\`bash
pip install ./${sdk.name.toLowerCase().replace(/\s+/g, '-')}-sdk
\`\`\`

## Features
- ✅ Zero-configuration setup
- ✅ Auto-healing security
- ✅ Real-time monitoring
- ✅ Quantum-safe encryption
- ✅ Multi-language support

## Quick Start

### JavaScript
\`\`\`javascript
const { encrypt, decrypt, generateKey } = require('./${sdk.name.toLowerCase().replace(/\s+/g, '-')}-sdk');

// Generate a key
const key = generateKey();

// Encrypt data
const encrypted = encrypt('Hello, World!', key);

// Decrypt data
const decrypted = decrypt(encrypted, key);
console.log(decrypted); // "Hello, World!"
\`\`\`

### Python
\`\`\`python
from ${sdk.name.toLowerCase().replace(/\s+/g, '_')}_sdk import encrypt, decrypt, generate_key

# Generate a key
key = generate_key()

# Encrypt data
encrypted = encrypt('Hello, World!', key)

# Decrypt data
decrypted = decrypt(encrypted, key)
print(decrypted)  # "Hello, World!"
\`\`\`

## Configuration
The SDK comes pre-configured for your environment:
- Application Type: ${sdk.applicationType}
- Security Level: ${sdk.securityLevel}
- Deployment: ${sdk.deploymentEnvironment}

## Support
Generated by Averox Crypto System - Enterprise Encryption Platform
Version: ${sdk.version}
Generated: ${new Date().toISOString()}

For support, visit: https://averox.com/support
Documentation: https://docs.averox.com
`;

      archive.append(readmeContent, { name: 'README.md' });

      // Generate package.json for Node.js
      if (languages.includes('javascript') || languages.includes('typescript')) {
        const packageJson = {
          name: `${sdk.name.toLowerCase().replace(/\s+/g, '-')}-sdk`,
          version: sdk.version,
          description: `${sdk.name} - Enterprise encryption SDK`,
          main: 'src/index.js',
          types: 'src/index.d.ts',
          scripts: {
            test: 'node test.js',
            build: 'echo "SDK ready to use"'
          },
          dependencies: {},
          keywords: ['encryption', 'security', 'averox', 'quantum-safe', 'enterprise'],
          author: 'Averox Crypto System',
          license: 'MIT'
        };
        archive.append(JSON.stringify(packageJson, null, 2), { name: 'package.json' });
      }

      // Generate setup.py for Python
      if (languages.includes('python')) {
        const setupPy = `from setuptools import setup, find_packages

setup(
    name="${sdk.name.toLowerCase().replace(/\s+/g, '-')}-sdk",
    version="${sdk.version}",
    description="${sdk.name} - Enterprise encryption SDK",
    packages=find_packages(),
    install_requires=[
        'cryptography>=3.0.0',
    ],
    python_requires='>=3.7',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'Topic :: Security :: Cryptography',
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
    ],
    author='Averox Crypto System',
    author_email='support@averox.com',
)`;
        archive.append(setupPy, { name: 'setup.py' });
      }

      // Generate actual working source files for each language
      await generateLanguageFiles(archive, languages, selectedAlgorithms, sdk, features);

      // Generate configuration file
      const config = generateAdvancedConfiguration(sdk, features, selectedAlgorithms);
      archive.append(JSON.stringify(config, null, 2), { name: 'averox.config.json' });

      // Example/test files
      if (languages.includes('javascript') || languages.includes('typescript')) {
        const testJS = `// ${sdk.name} SDK Test File
const { encrypt, decrypt, generateKey } = require('./src');

console.log('Testing ${sdk.name} SDK v${sdk.version}...');

try {
  // Generate a key
  const key = generateKey();
  console.log('✓ Key generated successfully');

  // Test encryption
  const testData = 'Hello, Averox Crypto System!';
  const encrypted = encrypt(testData, key);
  console.log('✓ Encryption successful');

  // Test decryption
  const decrypted = decrypt(encrypted, key);
  console.log('✓ Decryption successful');

  if (decrypted === testData) {
    console.log('✅ All tests passed! SDK is working correctly.');
  } else {
    console.error('❌ Test failed: Decrypted data does not match original');
  }
} catch (error) {
  console.error('❌ Test failed:', error.message);
}`;
        archive.append(testJS, { name: 'test.js' });
      }

      if (languages.includes('python')) {
        const testPy = `#!/usr/bin/env python3
"""${sdk.name} SDK Test File"""

from src import encrypt, decrypt, generate_key

print('Testing ${sdk.name} SDK v${sdk.version}...')

try:
    # Generate a key
    key = generate_key()
    print('✓ Key generated successfully')

    # Test encryption
    test_data = 'Hello, Averox Crypto System!'
    encrypted = encrypt(test_data, key)
    print('✓ Encryption successful')

    # Test decryption
    decrypted = decrypt(encrypted, key)
    print('✓ Decryption successful')

    if decrypted == test_data:
        print('✅ All tests passed! SDK is working correctly.')
    else:
        print('❌ Test failed: Decrypted data does not match original')
except Exception as error:
    print(f'❌ Test failed: {error}')
`;
        archive.append(testPy, { name: 'test.py' });
      }

      // Add error handling for archive completion
      archive.on('error', (err: any) => {
        console.error('Archive error:', err);
        res.status(500).json({ message: "Failed to create SDK archive" });
      });

      archive.on('end', () => {
        console.log('Archive finalized successfully');
      });

      // Finalize the archive
      await archive.finalize();

    } catch (error) {
      console.error("Error generating SDK download:", error);
      res.status(500).json({ message: "Failed to generate SDK download" });
    }
  });

  // Algorithm routes
  app.get('/api/algorithms', async (req, res) => {
    try {
      const algorithms = await storage.getEncryptionAlgorithms();
      res.json(algorithms);
    } catch (error) {
      console.error("Error fetching algorithms:", error);
      res.status(500).json({ message: "Failed to fetch algorithms" });
    }
  });

  // Key management routes
  app.get('/api/keys', isAuthenticated, async (req: any, res) => {
    try {
      const userId = req.user.claims.sub;
      const user = await storage.getUser(userId);
      
      if (!user?.tenantId) {
        return res.status(400).json({ message: "User not associated with a tenant" });
      }

      const keys = await storage.getEncryptionKeys(user.tenantId);
      res.json(keys);
    } catch (error) {
      console.error("Error fetching keys:", error);
      res.status(500).json({ message: "Failed to fetch keys" });
    }
  });

  app.post('/api/keys', isAuthenticated, async (req: any, res) => {
    try {
      const userId = req.user.claims.sub;
      const user = await storage.getUser(userId);
      
      if (!user?.tenantId) {
        return res.status(400).json({ message: "User not associated with a tenant" });
      }

      const validatedData = insertEncryptionKeySchema.parse({
        ...req.body,
        tenantId: user.tenantId,
      });

      const key = await storage.createEncryptionKey(validatedData);

      // Log security event
      await storage.createSecurityEvent({
        tenantId: user.tenantId,
        eventType: 'key_created',
        severity: 'medium',
        description: `Encryption key created: ${key.keyType}`,
        metadata: { keyId: key.id, algorithmId: key.algorithmId },
      });

      res.status(201).json(key);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ 
          message: "Invalid request data",
          errors: error.errors 
        });
      }
      console.error("Error creating key:", error);
      res.status(500).json({ message: "Failed to create key" });
    }
  });

  // Security events routes
  app.get('/api/security-events', isAuthenticated, async (req: any, res) => {
    try {
      const userId = req.user.claims.sub;
      const user = await storage.getUser(userId);
      
      if (!user?.tenantId) {
        return res.status(400).json({ message: "User not associated with a tenant" });
      }

      const { page = 1, limit = 50, severity, eventType } = req.query;
      const limitNumber = parseInt(limit as string);

      const events = await storage.getSecurityEvents(user.tenantId, limitNumber);
      res.json(events);
    } catch (error) {
      console.error("Error fetching security events:", error);
      res.status(500).json({ message: "Failed to fetch security events" });
    }
  });

  app.post('/api/security-events', isAuthenticated, async (req: any, res) => {
    try {
      const userId = req.user.claims.sub;
      const user = await storage.getUser(userId);
      
      if (!user?.tenantId) {
        return res.status(400).json({ message: "User not associated with a tenant" });
      }

      const validatedData = insertSecurityEventSchema.parse({
        ...req.body,
        tenantId: user.tenantId,
      });

      const event = await storage.createSecurityEvent(validatedData);
      res.status(201).json(event);
    } catch (error) {
      if (error instanceof z.ZodError) {
        return res.status(400).json({ 
          message: "Invalid request data",
          errors: error.errors 
        });
      }
      console.error("Error creating security event:", error);
      res.status(500).json({ message: "Failed to create security event" });
    }
  });

  // User management routes (admin only)
  app.get('/api/users', isAuthenticated, async (req: any, res) => {
    try {
      const userId = req.user.claims.sub;
      const user = await storage.getUser(userId);
      
      if (!user?.tenantId || user.role !== 'admin') {
        return res.status(403).json({ message: "Access denied" });
      }

      const users = await storage.getTenantUsers(user.tenantId);
      res.json(users);
    } catch (error) {
      console.error("Error fetching users:", error);
      res.status(500).json({ message: "Failed to fetch users" });
    }
  });

  app.put('/api/users/:targetUserId/role', isAuthenticated, async (req: any, res) => {
    try {
      const userId = req.user.claims.sub;
      const user = await storage.getUser(userId);
      
      if (!user?.tenantId || user.role !== 'admin') {
        return res.status(403).json({ message: "Access denied" });
      }

      const { targetUserId } = req.params;
      const { role } = req.body;

      if (!['admin', 'developer', 'viewer'].includes(role)) {
        return res.status(400).json({ message: "Invalid role" });
      }

      await storage.updateUserRole(targetUserId, role);

      // Log security event
      await storage.createSecurityEvent({
        tenantId: user.tenantId,
        eventType: 'user_role_changed',
        severity: 'medium',
        description: `User role changed to ${role}`,
        metadata: { targetUserId, newRole: role, changedBy: userId },
      });

      res.json({ message: "User role updated successfully" });
    } catch (error) {
      console.error("Error updating user role:", error);
      res.status(500).json({ message: "Failed to update user role" });
    }
  });

  // Tenant information
  app.get('/api/tenant', isAuthenticated, async (req: any, res) => {
    try {
      const userId = req.user.claims.sub;
      const user = await storage.getUser(userId);
      
      if (!user?.tenantId) {
        return res.status(400).json({ message: "User not associated with a tenant" });
      }

      const tenant = await storage.getTenant(user.tenantId);
      res.json(tenant);
    } catch (error) {
      console.error("Error fetching tenant:", error);
      res.status(500).json({ message: "Failed to fetch tenant" });
    }
  });

  const httpServer = createServer(app);
  return httpServer;
}